---
title: "SIR Model"
output:
  pdf_document: default
  html_document: default
date: "2025-06-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
```

```{r}
# parameter Setup

# Total Population 
N <- 10000

# Initial Setup
I_initial <- 1 # 1 person is infected
R_initial <- 0 # 0 person is recovered
S_initial <- N - I_initial - R_initial # everyone else is susceptible

# Time periods
days <- 365
dt <- 0.1
time <- seq(0, days, by = dt)

# Assumption of beta and gamma
gamma <- .05 # recovery rate
beta <- .15 # transmission rate
R_0 <- beta / gamma # basic reproduction number

# variables Setup
S <- numeric(length(time))
I <- numeric(length(time))
R <- numeric(length(time))
# Initial values
S[1] <- S_initial # S(0)
I[1] <- I_initial # I(0)
R[1] <- R_initial # R(0)

# Simulation #desolve
for (t in 1:(length(time) - 1)) {
  # Infection and recovery
  dS <- -beta * S[t] * I[t] / N
  dI <- beta * S[t] * I[t] / N - gamma * I[t]
  dR <- gamma * I[t]
  # Update values for next day
  S[t + 1] <- S[t] + dS * dt
  I[t + 1] <- I[t] + dI * dt
  R[t + 1] <- R[t] + dR * dt

}
head(data.frame(Day = time, S = S, I = I, R = R)) # Should I round values?

# Plot
sir_df <- data.frame(
  Day = time,
  S = S,
  I = I,
  R = R
)

sir_long <- pivot_longer(
  sir_df,
  cols = c("S", "I", "R"),
  names_to = "Compartment",
  values_to = "Count"
)

ggplot(data = sir_long, 
       mapping = aes(x = Day, y = Count, color = Compartment)) +
  geom_line(size = 1.2) +
  labs(
    title = paste("SIR Model Simulation (R0 =", R_0, ")"),
    x = "Time (days)",
    y = "Number of Individuals"
  ) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red", "green"))
```

